#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.1
# from Racc grammar file "".
#

require 'racc/parser.rb'

#
module SR
  class Parser < Racc::Parser

module_eval(<<'...end SmallRubyParser.y/module_eval...', 'SmallRubyParser.y', 68)
    def parse(tokens)
        @tokens = tokens
        do_parse
    end

    def next_token
        @tokens.shift
    end
...end SmallRubyParser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     2,    11,     2,     7,     8,     9,    19,     2,    11,    10,
     7,     8,     9,    19,     2,    11,    10,     7,     8,     9,
    19,     2,    11,    10,     7,     8,     9,    28,     2,    11,
    10,     7,     8,     9,    19,     2,    39,    10,     7,     8,
     9,    19,    38,     3,    10,     2,    11,     4,     7,     8,
     9,    19,     2,    11,    10,     7,     8,     9,    19,    43,
     5,    10,     2,    11,    22,     7,     8,     9,    28,     2,
    11,    10,     7,     8,     9,    19,     2,    11,    10,     7,
     8,     9,    19,    20,    36,    10,    40,    49,    52,    56,
    23,    21,    21,    34,    21,    21,    21,    21,    32,    35,
    24,    21,    47,    48,   -26,    24,    50,    51,    26,    21,
    21,    54,    21 ]

racc_action_check = [
     4,     4,     0,     4,     4,     4,     4,    19,    19,     4,
    19,    19,    19,    19,    22,    22,    19,    22,    22,    22,
    22,    23,    23,    22,    23,    23,    23,    23,    24,    24,
    23,    24,    24,    24,    24,    28,    28,    24,    28,    28,
    28,    28,    28,     1,    28,    30,    30,     2,    30,    30,
    30,    30,    34,    34,    30,    34,    34,    34,    34,    34,
     3,    34,    35,    35,     7,    35,    35,    35,    35,    46,
    46,    35,    46,    46,    46,    46,    51,    51,    46,    51,
    51,    51,    51,     6,    27,    51,    29,    41,    45,    53,
    10,     6,    27,    26,    29,    41,    45,    53,    25,    26,
    11,    25,    37,    37,    39,    39,    44,    44,    21,    31,
    42,    48,    55 ]

racc_action_pointer = [
     0,    43,    44,    60,    -2,   nil,    79,    61,   nil,   nil,
    87,    87,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,
   nil,   105,    12,    19,    26,    89,    85,    80,    33,    82,
    43,    97,   nil,   nil,    50,    60,   nil,    93,   nil,    92,
   nil,    83,    98,   nil,    97,    84,    67,   nil,   108,   nil,
   nil,    74,   nil,    85,   nil,   100,   nil ]

racc_action_default = [
   -30,   -30,   -30,   -30,   -29,    57,   -30,   -30,    -3,    -4,
   -30,   -26,   -20,   -21,   -22,   -23,   -24,   -25,   -27,   -29,
    -1,   -30,   -29,   -29,   -29,   -30,   -11,   -30,   -29,   -30,
   -29,   -17,   -28,   -12,   -29,   -29,    -2,   -30,    -6,    -7,
    -9,   -30,   -15,   -13,   -30,   -30,   -29,    -5,   -30,   -10,
   -14,   -29,   -18,   -30,    -8,   -16,   -19 ]

racc_goto_table = [
     6,    30,     1,    37,    33,    44,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    46,   nil,   nil,   nil,   nil,    27,    29,
    31,   nil,   nil,   nil,   nil,   nil,    41,   nil,   nil,   nil,
    42,    45,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    53,   nil,   nil,   nil,   nil,    55 ]

racc_goto_check = [
     2,     6,     1,     7,    10,    11,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,     2,     2,
     2,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,
     2,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     2,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     2,    -4,   nil,   nil,   nil,   -22,   -25,   nil,   nil,
   -22,   -29,   nil ]

racc_goto_default = [
   nil,    12,    25,    13,    17,    16,   nil,   nil,    14,    15,
   nil,   nil,    18 ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 16, :_reduce_1,
  4, 18, :_reduce_2,
  1, 19, :_reduce_3,
  1, 20, :_reduce_4,
  3, 21, :_reduce_5,
  2, 21, :_reduce_6,
  1, 22, :_reduce_7,
  3, 22, :_reduce_8,
  4, 23, :_reduce_9,
  5, 23, :_reduce_10,
  3, 24, :_reduce_11,
  4, 24, :_reduce_12,
  5, 24, :_reduce_13,
  6, 24, :_reduce_14,
  1, 26, :_reduce_15,
  3, 26, :_reduce_16,
  3, 27, :_reduce_17,
  3, 25, :_reduce_18,
  4, 25, :_reduce_19,
  1, 17, :_reduce_none,
  1, 17, :_reduce_none,
  1, 17, :_reduce_none,
  1, 17, :_reduce_none,
  1, 17, :_reduce_none,
  1, 17, :_reduce_none,
  1, 17, :_reduce_none,
  1, 17, :_reduce_none,
  3, 17, :_reduce_28,
  0, 17, :_reduce_29 ]

racc_reduce_n = 30

racc_shift_n = 57

racc_token_table = {
  false => 0,
  :error => 1,
  "module" => 2,
  :CONST => 3,
  "end" => 4,
  "class" => 5,
  :STRING => 6,
  :NUMBER => 7,
  "(" => 8,
  ")" => 9,
  "," => 10,
  "def" => 11,
  "." => 12,
  "=" => 13,
  "do" => 14 }

racc_nt_base = 15

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"module\"",
  "CONST",
  "\"end\"",
  "\"class\"",
  "STRING",
  "NUMBER",
  "\"(\"",
  "\")\"",
  "\",\"",
  "\"def\"",
  "\".\"",
  "\"=\"",
  "\"do\"",
  "$start",
  "module",
  "exp",
  "class",
  "string",
  "number",
  "args",
  "argsList",
  "def",
  "send",
  "block",
  "expList",
  "assign" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'SmallRubyParser.y', 3)
  def _reduce_1(val, _values, result)
     result = [:module,val[1],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 5)
  def _reduce_2(val, _values, result)
     result = [:class,val[1],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 7)
  def _reduce_3(val, _values, result)
    result = [:string,val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 10)
  def _reduce_4(val, _values, result)
    result = [:number,val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 13)
  def _reduce_5(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 15)
  def _reduce_6(val, _values, result)
    result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 18)
  def _reduce_7(val, _values, result)
    result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 20)
  def _reduce_8(val, _values, result)
    result.push(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 23)
  def _reduce_9(val, _values, result)
    result = [:def,val[1],[],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 25)
  def _reduce_10(val, _values, result)
    result = [:def,val[1],val[2],val[3]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 28)
  def _reduce_11(val, _values, result)
     result = [:send,val[0],val[2],[]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 30)
  def _reduce_12(val, _values, result)
     result = [:send,val[0],val[2],[],val[3]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 32)
  def _reduce_13(val, _values, result)
     result = [:send,val[0],val[2],[]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 34)
  def _reduce_14(val, _values, result)
     result = [:send,val[0],val[2],val[4]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 37)
  def _reduce_15(val, _values, result)
    result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 39)
  def _reduce_16(val, _values, result)
    result.push(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 42)
  def _reduce_17(val, _values, result)
    result = [:assign,val[0],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 45)
  def _reduce_18(val, _values, result)
    result = [:block,[],val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 47)
  def _reduce_19(val, _values, result)
    result = [:block,val[1],val[2]]
    result
  end
.,.,

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

module_eval(<<'.,.,', 'SmallRubyParser.y', 60)
  def _reduce_28(val, _values, result)
     result=val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'SmallRubyParser.y', 62)
  def _reduce_29(val, _values, result)
    result = []
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module SR

#
